-- Populate database with content from CSV file
-- This migration imports all the content from WILDWOOD_CONTENT - Sheet1.csv

-- Update content table with hero and contact information
UPDATE OR IGNORE content SET value = 'Wildwoods Studio' WHERE key = 'hero_title';
UPDATE OR IGNORE content SET value = 'Connecting you to yourself, others, and the Earth.' WHERE key = 'hero_subtitle';
UPDATE OR IGNORE content SET value = '801-310-7119' WHERE key = 'contact_phone';
UPDATE OR IGNORE content SET value = 'emily.lacey@gmail.com' WHERE key = 'contact_email';

-- Insert studio services
INSERT OR IGNORE INTO services (category, title, description, price, duration, detail_text, has_detail_page) VALUES
('studio', 'StickWork', 'StickWork Neural System Retraining is an active nervous system training system that rewires habitual tension into calm and ease. This is the most powerful and rapidly life changing thing I have experienced and I love being able to bring this to you. Is it challenging? Yes. But it changes you and gives you a chance to change the trajectory of your life, modify the way you experience and interpret the world, and space to choose instead of being tied to habits and learned patterns that no longer serve you. Many people find it very useful as an active recovery or maintinence tool as well.', 100.00, 90, 'Stickwork is an active process of nervous system training and somatic education. This approach bypasses the thinking mind and directly accesses the nervous system. We endeavor to address all layers of your system so the trauma, pain, and addictions have no where left to hide. This is not massage, but like an internal martial arts training where together, we are teaching your body to dissolve the conflict within and learn new ways to interpret and interact with the world. This is a powerful tool to reboot and redirect your life. Each session is as unique as you and the challenges you are facing. Training sessions can range from movement excercises and practicing relaxation in a BodyRock session to a full stickwork session with various implements like the sticks and percussion tools being used for deep release and retraining. All StickWork sessions include an intake call, skills to practice at home, and a follow up conversation. Because we are changing your perception and interaction with the world, it is recommended that in the beginning, you schedule 3-5 sessions 1-2 weeks apart as you learn to live with more freedom, choice, and joy.  My children regularly ask for sessions as it helps them overcome discomfort and pain and relieve built up tension and anxiety. There are many options available to help you where you are stuck or need support. Call for a free consultation.', TRUE),

('studio', 'Group Education', 'Experience a variety of simple ways to adjust the way you live to create more ease and joy in your life. Topics range from Human Design, using touch to connect and improve bonding and trust with your family, essential oil basics, and breathwork and grounding techniques intended to support you as you create a more enjoyable and pleasant life.', 10.00, 60, 'Calendar? $10.00 per Class', TRUE),

('studio', 'DōTerra Essential Oils', 'Essential oils are used in most sessions as I have found the results to be noticeably and often dramatically more positive and powerful. Classes about how to use oils to improve health and quality of life are offered.  To purchase your own essential oils and products visit https://referral.doterra.me/10479', 0.00, 60, 'Essential oils education and product information.', TRUE);

-- Insert nature services
INSERT OR IGNORE INTO services (category, title, description, price, duration, detail_text, has_detail_page) VALUES
('nature', 'Forest School', 'Forest School is a once a week class for elementary to middle school aged children. The intent of Forest School is to bring children to nature where they gain confidence and self sufficiency, learn teamwork, practice being alone, expand their curiosity and problem solving skills, and build respect and awe for creation.', 0.00, 120, 'Forest School is tailored by age group. We study a wide range of topics that rotates through the years but has included History: Native American, Norse, and Roman Mythology; Science: Earth science, biology, and astronomy, local geographical history; Art: singing, rhythm sticks, drumming, water colors, drawing, found nature art, role playing and readers theatre; Crafts: building bird houses and flower presses, pottery, carving, paper making, lantern crafting; Writing: poetry, observations, journaling; and Sports: ice hockey, ice skating, cross country skiing, hiking, cold water exploration, and numerous group games; Wilderness Skills: fire, cooking over a fire, shelters, first aid and safety skills, knives. Younger classes include more imaginative play such as house and town, water play, fairy villages, parachute, fables and nursery rhymes, and so on.

At this time, we meet on Tuesday morning. Enrollment is currently closed, but stayed tuned for future offereings.', TRUE),

('nature', 'Forest Bathing', 'This is adult and teen focused and is customizable for private groups or you can join a scheduled group outing. The basic structure consists of traveling to a forest location, participating in a forest therapy activity intended to bring you in direct contact with the earth, practice guided meditation and breathing activities, reflect as a group, and return home. My most enjoyable versions of this begin with simply hiking to a unique geographical location or cross country skiing out and sitting in hammocks and then participating in the forest bathing activity. Check the calendar to join a scheduled event or contact Emily to set up a private outing.', 25.00, 120, 'Customizable forest therapy experiences for adults and teens.', TRUE),

('nature', 'Special Occasions', 'The Earth offers the perfect setting to mark significant events or to support you through grief, transitions, or celebrations. I would be honored to facilitate a passage of this sort for you or your family. This is only offered as a custom experience. Please contact me to discuss your desire and vision and see if what I can offer matches your needs.', 0.00, 60, 'Custom nature-based experiences for special occasions and life transitions.', TRUE);
